# CI PowerShell Validation

name: PowerShell tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'helpers/**'

permissions:
  contents: read

jobs:
  powershell-tests:
    name: PowerShell tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run tests
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force
          Invoke-Pester -Output Detailed "helpers/software-report-base/tests"
        