name: Sync with Upstream (create)

on:
  schedule:
    - cron: "0 0 1 * *" # Runs at 00:00 on the first day of every month
  workflow_dispatch:
  # TODO: Remove this trigger once the workflow is ready
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    # TODO: Remove this condition once the workflow is ready
    if: github.event.pull_request.user.login != 'github-actions[bot]'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          ref: main

      - name: Create new branch from main
        run: |
          git checkout -b sync-upstream-${{ github.run_number }}

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      #TODO: Remove this step once the workflow is ready
      - name: Merge the feature branch for the workflow
        run: |
          git merge --squash origin/gc/sync-upstream
          git commit -m "Add sync-upstream.yml workflow (#7)"

      - name: Pull changes from upstream and merge
        id: merge
        run: |
          git remote add upstream https://github.com/actions/runner-images.git
          git fetch upstream
          SHA="$(git rev-parse upstream/main)"
          echo "upstream-sha=$SHA" >> $GITHUB_OUTPUT
          if ! git merge -m "Merge commit '$SHA' from actions/runner-images" "${SHA}"; then
            echo "conflicts=true" >> $GITHUB_OUTPUT
          fi

      - name: Handle conflicts with empty commit
        if: steps.merge.outputs.conflicts == 'true'
        run: |
          git merge --abort
          git commit --allow-empty -m "Empty commit due to merge conflicts"

      - name: Push changes to new branch
        run: |
          git push --force-with-lease origin sync-upstream-${{ github.run_number }}

      - name: Set PR body
        id: pr-body
        env:
          GITHUB_SERVER_URL: "${{ github.server_url }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_RUN_ID: "${{ github.run_id }}"
          GITHUB_RUN_NUMBER: "${{ github.run_number }}"
          UPSTREAM_SHA: "${{ steps.merge.outputs.upstream-sha }}"
          PR_BODY_NO_CONFLICTS_TEMPLATE: ".github/workflows/sync-upstream/templates/pr-body-no-conflicts.txt"
          PR_BODY_WITH_CONFLICTS_TEMPLATE: ".github/workflows/sync-upstream/templates/pr-body-with-conflicts.txt"
        run: |
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          if [ "${{ steps.merge.outputs.conflicts }}" == "true" ]; then
            envsubst < $PR_BODY_WITH_CONFLICTS_TEMPLATE  >> $GITHUB_OUTPUT
          else
            envsubst < $PR_BODY_NO_CONFLICTS_TEMPLATE  >> $GITHUB_OUTPUT
          fi
          echo EOF >> $GITHUB_OUTPUT

      # TODO: Change base branch once the workflow is ready
      - name: Create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --title 'Update from upstream' \
          --body '${{ steps.pr-body.outputs.body }}' \
          --base gc/test --head sync-upstream-${{ github.run_number }} \
          --repo ${{ github.repository }} \
          || \
          gh pr edit sync-upstream-${{ github.run_number }} \
          --repo ${{ github.repository }} \
          --body '${{ steps.pr-body.outputs.body }}'
