name: Build and Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build-and-publish:
    permissions:
      contents: write
      id-token: write
    uses: grafana/runner-images/.github/workflows/packer-build-and-publish.yml@main
