name: Build and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    # TODO: Revert back to @main before the PR is merged
    uses: grafana/runner-images/.github/workflows/packer-build-and-publish.yml@gc/update-to-ubuntu-24
