name: Trigger Build workflow

on:
  workflow_call:
    inputs:
      image_type:
        required: true
        type: string
    secrets:
      CI_PR_TOKEN:
        required: true
      CI_REPO:
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  trigger-workflow:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build workflow
        env:
          CI_PR_TOKEN: ${{ secrets.CI_PR_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          CI_PR: ${{ secrets.CI_REPO }}
          IMAGE_TYPE: ${{ inputs.image_type }}
          REPO_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          $headers = @{
            Authorization="Bearer $env:CI_PR_TOKEN"
          }

          # Private repository for builds
          $apiRepoUrl = "https://api.github.com/repos/$env:CI_PR"

          $eventType = "trigger-$env:IMAGE_TYPE-build"
          $body = @{
            event_type = $eventType;
            client_payload = @{
              pr_title = "$env:PR_TITLE"
              custom_repo = "$env:REPO_FULL_NAME"
              custom_repo_commit_hash = "$env:COMMIT_SHA"
            }
          }

          $bodyString = $body | ConvertTo-Json

          try {
            Invoke-WebRequest -Uri "$apiRepoUrl/dispatches" -Method Post -Headers $headers -Body $bodyString | Out-Null
          } catch {
            throw "$($_.exception[0].message)"
          }
