name: Trigger Windows25 CI
run-name: Windows2025 - ${{ github.event.pull_request.title }}

on:
  pull_request:
    types: labeled
    paths:
    - 'images/windows/**'

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  Windows_2025:
    permissions:
      contents: read
    if: github.event.label.name == 'CI windows-all' || github.event.label.name == 'CI windows-2025'
    uses: ./.github/workflows/trigger-ubuntu-win-build.yml
    with:
      image_type: 'windows2025'
    secrets:
      CI_PR_TOKEN: ${{ secrets.CI_PR_TOKEN }}
      CI_REPO: ${{ secrets.CI_REPO }}
